version: '3.4'

services:
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  todo.web:
    image: ${DOCKER_REGISTRY-}todoweb
    build:
      context: .
      dockerfile: OmerOzkan.ToDo.Web/Dockerfile


